version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mellowq-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mellowq
    volumes:
      - mongodb_data:/data/db
    networks:
      - mellowq-network

volumes:
  mongodb_data:
    driver: local

networks:
  mellowq-network:
    driver: bridge